<?php
require("classes/security.php");
$pageTitle = "Level 1";
$practiceCategories = "";
if(isset($_GET["practiceCategories"])){
    $practiceCategories = $_GET["practiceCategories"];
    $pageTitle = "Practice";
}

require("header.php");
$drupalUserID = $_SESSION["drupalUserID"];
if (isset($_GET["debug"])) {
    $_SESSION["debug"] = true;
}


?>


<script language="javascript" type="text/javascript">
    /*
        RULES FOR LEVEL 1:
        1. This level has 5 questions
        2. Each question shows 4 images - only one image is the correct answer / match
            for the presented diagnosis
        3. Each correct answer earns 100 points
        4. If learner misses 2 questions, the learner fails Level 1 and has to repeat it
        5. If learner answers all 5 questions correctly, the Level 1 awards a 300-point bonus
        6. All levels have a time-based performance bonus:
                a. Time-based bonus has an initial value of 300 points
                b. For each second spent on Level 1 learner loses 5 points from the time-based bonus
    */
    
    
    
    /******************************************************************************
    Global variable declarations
    ******************************************************************************/
    
    var levelQuestionList = null;   // All questions for this level
    
    /*
        Object that stores a single question retrieved from the JSON array stored in levelQuestionList
    */
    var levelID = 1;
    var question = null;            
    var levelAttempts = 1;          // Number of times this level has been attempted
    var questionsCompleted = 0;     // Number of questions answered (correctly or incorrectly)
    var numberCorrect = 0;          // Number of correct answers in a level attempt
    var numberIncorrect = 0;        // Number of incorrect answers in a level attempt
    var currentScore = 0;           // Learner's current score
    var imageList = null;           // ????
    var timerID = 0;                // Tracks ID generated by setInterval()
    var redirectTimerID = 0;
    var timeBonus = 300;            // Time-based bonus for Level 1
    var levelPassed = false;
    var gameAttemptID = '<?php echo $_SESSION["gameAttemptID"]; ?>';
    var drupalUserID = '<?php echo $drupalUserID; ?>';
    var practiceCategories = '<?php echo $practiceCategories; ?>';
    
    // console.log(practiceCategories);
    
    
    // Wait until the document has been loaded into the browser
    $(document).ready(function(){
        if(getUrlParameter('levelAttempts')){
            levelAttempts = getUrlParameter('levelAttempts');
        }
        
        if(practiceCategories != ""){ //practice category specified
            $(".scores-parent").css({
                "visibility" : "hidden",
                "display" : "none"
            })
            
            $(".level-num").html("Practice Mode");
        }
        else{ //practice category not specified
            $(".next-question-button").css({
                "visibility" : "hidden",
                "display" : "none"
            });
        }
        updateScoreBoard();
        initQuestion();
        
        /* Hide overlay (zoom window) when escape key is pressed */
        $(document).keyup(function(evt){
            if(evt.keyCode == 27){
                $('#overlay').css('display', 'none');
            } 
        }); // end of "hide zoom overlay" logic
        
        /* 
            All levels use time-based bonuses.  For Level 1, the initial value of a time-based
            bonus is 300 points.  For each second spent on the level, learner loses 5 points from 
            the time-based bonus. 
            The following line initializes a timer-based function that subtracts 5 points from the 
            initial bonus value every 5 seconds
        */
        timerID = setInterval('updateTimeBonus', 1000);
    });
    
    
    function initQuestion(){
        /* Show overlay with loading icon */
        $('#loadingOverlay').css('display', 'block');
        
        // Concat. URI to the web service
        var uri = "rest/question_ws_obj.php?levelID=" + levelID + "&gameAttemptID=" + gameAttemptID;
        if(practiceCategories != ""){
            uri += "&practiceCategories=" + practiceCategories;
        }
        console.log(uri);
        $.getJSON(uri, function(data){
            /* Set global variable to the value of the JSON array retreived from the web service */
            levelQuestionList = data; 
            
            /* Load the question */
            getQuestion(levelQuestionList);
            
            /* Hide overlay with loading icon */
            $('#loadingOverlay').css('display', 'none');
        });    
    }
    
    function selectDxImage(buttonObj){
        var selectedImage = getSelectedImageData($(buttonObj));
        // console.log(selectedImage);
        if(selectedImage){
            highlightCorrectIncorrect(levelQuestionList);
            if(practiceCategories == ""){
                if(selectedImage.isCorrectChoice){
                    numberCorrect = numberCorrect + 1;
                    currentScore = currentScore + 100;
                }
                else{
                    numberIncorrect = numberIncorrect + 1;
                }

                questionsCompleted = questionsCompleted + 1;
                /********************************************************
                Logic for success
                ********************************************************/
                if(questionsCompleted == 5){
                    if(numberCorrect == 5){
                        currentScore = currentScore + 300;
                    }
                    currentScore = currentScore + timeBonus;
                    clearInterval(timerID);
                    levelPassed = true;
                    updateScoreLog(gameAttemptID, 1, drupalUserID, levelAttempts, 1, currentScore, questionsCompleted, numberCorrect, numberIncorrect);
                }
                /********************************************************
                End logic for success
                ********************************************************/




                /********************************************************
                Logic for failed level
                ********************************************************/
                if(numberIncorrect == 2){
                    // Reset all counters
                    // levelAttempts = levelAttempts + 1;
                    numberCorrect = 0;
                    numberIncorrect = 0;
                    questionsCompleted = 0;
                    timeBonus = 300;
                    currentScore = 0;
                    updateScoreLog(gameAttemptID, 1, drupalUserID, levelAttempts, 0, currentScore, questionsCompleted, numberCorrect, numberIncorrect);
                    document.location.href = "completedlevelsummary.php?levelID=1";
                }
                /********************************************************
                End logic for failed level
                ********************************************************/


                updateScoreBoard();
            } // End of "Not practice mode"
            
            
            
            if(practiceCategories == ""){ //Practice category not specified
                redirectTimerID = setInterval(countRedirect, 2000);
                updateAnswerLog(gameAttemptID, 1, levelAttempts, drupalUserID, selectedImage.associatedDiagnosisID, selectedImage.imageID, selectedImage.isCorrectChoice); 
            }
            
            
            
        }
        
    }
    
    
    

</script>

<?php

?>
<div class="container">
  <div class="questions-div">
    <div class="question-box">
      <h1 class="level-num"> Level 1: Multiple Choice </h1>
      <h3>
          <!--
          The following php code brings up the different questions and hints tied to each question.
          -->
          Which of these images represents:</h3><br /> <h3 class='disease' id='questionText'></h3>
          
      
      <div class = "hint">
          <button type="button" id="hintButton" class="hintBtn" data-toggle="tooltip" data-placement="top" title=  ""; data-original-title="Tooltip on top">HINT</button>
      </div>
        
    </div>

    <div class="scores-parent">
      <div class="scores-child dark" id="divLevelAttempts"> # Level Attempts: 1</div>
      <div class="scores-child" id="divQuestionsAnswered"> Questions Completed: 0</div>
      <div class="scores-child dark" id="divNumberCorrect"> Number Correct: 0</div>
      <div class="scores-child" id="divCurrentScore"> Your Score: 0</div>
    </div>
      
    <div class="next-question-button">
        <center>
            <input type="button" id="nextQuestion" class="btn" title="Next Question" value="NEXT QUESTION" onclick="initQuestion();" />
        </center>
    </div>
  </div><!--end questions -->

  <div class="answers-div">
    <!--
    The following php code creates an image container and slider that contain the images  that are randomly generated from the database and based off of the question and answer.
    -->
    <div class='answers-row'>
        <div class='imageContainer'>
            <div class='selectors' style='width:55%;'>
                <input type='button' value='SELECT' class='imageSelector' onclick='selectDxImage(this);' />
            </div>
            <div class='selectors' style='width:45%;'>
                <img src='images/magnify.png' class='magnify' />
            </div>
            <img class='intense' height='250' />
        </div>
        <div class='imageContainer'>
            <div class='selectors' style='width:55%;'>
                <input type='button' value='SELECT' class='imageSelector' onclick='selectDxImage(this);' />
            </div>
            <div class='selectors' style='width:45%;'>
                <img src='images/magnify.png' class='magnify' />
            </div>
            <img class='intense' height='250' />
        </div>
    </div>
    <div class='answers-row'>
        <div class='imageContainer'>
            <div class='selectors' style='width:55%;'>
                <input type='button' value='SELECT' class='imageSelector' onclick='selectDxImage(this);' />
            </div>
            <div class='selectors' style='width:45%;'>
                <img src='images/magnify.png' class='magnify' />
            </div>
            <img class='intense' height='250' />
        </div>
        <div class='imageContainer'>
            <div class='selectors' style='width:55%;'>
                <input type='button' value='SELECT' class='imageSelector' onclick='selectDxImage(this);' />
            </div>
            <div class='selectors' style='width:45%;'>
                <img src='images/magnify.png' class='magnify' />
            </div>
            <img class='intense' height='250' />
        </div>
    </div>

    
    <div id='dialog-confirm' title='Important'>
        <p>
            <span class='ui-icon ui-icon-alert' style='visibility: hidden; float:left; margin:0 7px 20px 0;'>
            </span>
        </p>
      </div>
  </div>
</div><!--end container -->



<?php
require("footer.php");
?>
